public class Library {
	public static void main(String[] args){		
		long startTime = System.currentTimeMillis();		
		
		BookIndexer61715 bookIndexer = new BookIndexer61715();
		bookIndexer.buildIndex("bigTest.txt", sampleKeywords, "bigTestIndex.txt");
		
		// duration: 1453 on my PC...
		System.out.println("duration: " + (System.currentTimeMillis() - startTime));
	}
	
	private static String[] sampleKeywords = new String[]{ "Lorem", "ipsum","dolor","modo", "Epicuri",
        "sint", "Hoc", "autem", "quae", "appetendi", "extrema", "grave", "tamen",
        "puto", "nobis",  "medicina",  "navigationis", "Vivendi", "intellegendum",
        "ipsa", "future", "turpe", "partem", "dixisset", "placet", "complexa", "esse",
        "sententiam", "claris", "viris", "nec", "laudatores", "aliud", "ita",
        "natum", "sic", "ferarum", "natura", "quasdam", "post", "mortem", "formidines",
        "extimescant", "discessu", "suis", "atque", "ipsa", "relinquenda", "luce",
        "moveatur", "naturam", "stupraretur", "Summum", "pecudis", "bonum", "hominis",
        "idem", "mihi", "videri", "potest", "Nihil", "enim", "est", "aliud", "quam",
        "percipi", "nihil", "posse", "videatur", "percipiendi", "definitur", "Stoicis",
        "Homine", "autem", "summa", "omnis", "animi", "animo", "rationis", "virtus",
        "Optimos", "viros", "hominess", "doctissimos", "virtus", "corporis", "virtuti",
        "anteponatur", "animique", "virtutes", "voluntarias", "vincant", "virtutes",
        "voluntariae", "quidem", "proprie", "virtutes", "appellantur", "multumque",
        "excellunt", "propterea", "quod", "ratione", "gignuntur", "homine", "divinius",
        "aliquid", "rebus", "probabile", "Nimium", "festinanter", "dictum", "videtur",
        "sapientis", "Quamquam", "verba", "quibus", "instituto", "veterum", "utimur",
        "Latinis", "philosophia", "dialectica", "grammatica", "geometria", "musica",
        "quamquam", "Latine", "Etiam", "tractare", "coepimus", "suppeditabit", "nobis",
        "Atticus", "noster", "quantos", "viros", "none", "melius", "quam", "Quae",
        "vobis", "talia", "dicerentur", "qualibus", "uti", "poterat", "expulsus",
        "egens", "palude", "demersus", "tropaeorum", "recordation", "leveret",
        "dolorem",  "audirem", "plane", "probarem",  "haec", "loquitur", "voluptate",
        "nihil", "ponens", "negat", "bene", "cenare", "omnia", "ponat", "voluptate",
        "tamen", "negat", "libenter", "cenasse", "umquam", "Galloniummentiretur",
        "enim", "sed", "bene", "Itaque", "solum", "incommoda", "eveniunt", "inprobis",
        "fugiendam", "inprobitatem", "putamus", "multo", "etiam", "magis", "quod",
        "cuius", "animo", "versatur", "numquam", "sinit", "respirare", "numquam",
        "adquiescere", "Eodem", "Ergo", "eadem", "voluptate", "alteri", "misceat",
        "Fadio", "Gallo", "cuius", "testament", "Aaaaaa", "aaaaab", "aaaaaac", "aaaaaad", "zzzzzzzx",
        "Lorem", "ipsum","dolor","modo", "Epicuri",
        "sint", "Hoc", "autem", "quae", "appetendi", "extrema", "grave", "tamen",
        "puto", "nobis",  "medicina",  "navigationis", "Vivendi", "intellegendum",
        "ipsa", "future", "turpe", "partem", "dixisset", "placet", "complexa", "esse",
        "sententiam", "claris", "viris", "nec", "laudatores", "aliud", "ita",
        "natum", "sic", "ferarum", "natura", "quasdam", "post", "mortem", "formidines",
        "extimescant", "discessu", "suis", "atque", "ipsa", "relinquenda", "luce",
        "moveatur", "naturam", "stupraretur", "Summum", "pecudis", "bonum", "hominis",
        "idem", "mihi", "videri", "potest", "Nihil", "enim", "est", "aliud", "quam",
        "percipi", "nihil", "posse", "videatur", "percipiendi", "definitur", "Stoicis",
        "Homine", "autem", "summa", "omnis", "animi", "animo", "rationis", "virtus",
        "Optimos", "viros", "hominess", "doctissimos", "virtus", "corporis", "virtuti",
        "anteponatur", "animique", "virtutes", "voluntarias", "vincant", "virtutes",
        "voluntariae", "quidem", "proprie", "virtutes", "appellantur", "multumque",
        "excellunt", "propterea", "quod", "ratione", "gignuntur", "homine", "divinius",
        "aliquid", "rebus", "probabile", "Nimium", "festinanter", "dictum", "videtur",
        "sapientis", "Quamquam", "verba", "quibus", "instituto", "veterum", "utimur",
        "Latinis", "philosophia", "dialectica", "grammatica", "geometria", "musica",
        "quamquam", "Latine", "Etiam", "tractare", "coepimus", "suppeditabit", "nobis",
        "Atticus", "noster", "quantos", "viros", "none", "melius", "quam", "Quae",
        "vobis", "talia", "dicerentur", "qualibus", "uti", "poterat", "expulsus",
        "egens", "palude", "demersus", "tropaeorum", "recordation", "leveret",
        "dolorem",  "audirem", "plane", "probarem",  "haec", "loquitur", "voluptate",
        "nihil", "ponens", "negat", "bene", "cenare", "omnia", "ponat", "voluptate",
        "tamen", "negat", "libenter", "cenasse", "umquam", "Galloniummentiretur",
        "enim", "sed", "bene", "Itaque", "solum", "incommoda", "eveniunt", "inprobis",
        "fugiendam", "inprobitatem", "putamus", "multo", "etiam", "magis", "quod",
        "cuius", "animo", "versatur", "numquam", "sinit", "respirare", "numquam",
        "adquiescere", "Eodem", "Ergo", "eadem", "voluptate", "alteri", "misceat",
        "Fadio", "Gallo", "cuius", "testament", "Aaaaaa", "aaaaab", "aaaaaac", "aaaaaad", "zzzzzzzx",
        "Lorem", "ipsum","dolor","modo", "Epicuri",
        "sint", "Hoc", "autem", "quae", "appetendi", "extrema", "grave", "tamen",
        "puto", "nobis",  "medicina",  "navigationis", "Vivendi", "intellegendum",
        "ipsa", "future", "turpe", "partem", "dixisset", "placet", "complexa", "esse",
        "sententiam", "claris", "viris", "nec", "laudatores", "aliud", "ita",
        "natum", "sic", "ferarum", "natura", "quasdam", "post", "mortem", "formidines",
        "extimescant", "discessu", "suis", "atque", "ipsa", "relinquenda", "luce",
        "moveatur", "naturam", "stupraretur", "Summum", "pecudis", "bonum", "hominis",
        "idem", "mihi", "videri", "potest", "Nihil", "enim", "est", "aliud", "quam",
        "percipi", "nihil", "posse", "videatur", "percipiendi", "definitur", "Stoicis",
        "Homine", "autem", "summa", "omnis", "animi", "animo", "rationis", "virtus",
        "Optimos", "viros", "hominess", "doctissimos", "virtus", "corporis", "virtuti",
        "anteponatur", "animique", "virtutes", "voluntarias", "vincant", "virtutes",
        "voluntariae", "quidem", "proprie", "virtutes", "appellantur", "multumque",
        "excellunt", "propterea", "quod", "ratione", "gignuntur", "homine", "divinius",
        "aliquid", "rebus", "probabile", "Nimium", "festinanter", "dictum", "videtur",
        "sapientis", "Quamquam", "verba", "quibus", "instituto", "veterum", "utimur",
        "Latinis", "philosophia", "dialectica", "grammatica", "geometria", "musica",
        "quamquam", "Latine", "Etiam", "tractare", "coepimus", "suppeditabit", "nobis",
        "Atticus", "noster", "quantos", "viros", "none", "melius", "quam", "Quae",
        "vobis", "talia", "dicerentur", "qualibus", "uti", "poterat", "expulsus",
        "egens", "palude", "demersus", "tropaeorum", "recordation", "leveret",
        "dolorem",  "audirem", "plane", "probarem",  "haec", "loquitur", "voluptate",
        "nihil", "ponens", "negat", "bene", "cenare", "omnia", "ponat", "voluptate",
        "tamen", "negat", "libenter", "cenasse", "umquam", "Galloniummentiretur",
        "enim", "sed", "bene", "Itaque", "solum", "incommoda", "eveniunt", "inprobis",
        "fugiendam", "inprobitatem", "putamus", "multo", "etiam", "magis", "quod",
        "cuius", "animo", "versatur", "numquam", "sinit", "respirare", "numquam",
        "adquiescere", "Eodem", "Ergo", "eadem", "voluptate", "alteri", "misceat",
        "Fadio", "Gallo", "cuius", "testament", "Aaaaaa", "aaaaab", "aaaaaac", "aaaaaad", "zzzzzzzx",
        "Lorem", "ipsum","dolor","modo", "Epicuri",
        "sint", "Hoc", "autem", "quae", "appetendi", "extrema", "grave", "tamen",
        "puto", "nobis",  "medicina",  "navigationis", "Vivendi", "intellegendum",
        "ipsa", "future", "turpe", "partem", "dixisset", "placet", "complexa", "esse",
        "sententiam", "claris", "viris", "nec", "laudatores", "aliud", "ita",
        "natum", "sic", "ferarum", "natura", "quasdam", "post", "mortem", "formidines",
        "extimescant", "discessu", "suis", "atque", "ipsa", "relinquenda", "luce",
        "moveatur", "naturam", "stupraretur", "Summum", "pecudis", "bonum", "hominis",
        "idem", "mihi", "videri", "potest", "Nihil", "enim", "est", "aliud", "quam",
        "percipi", "nihil", "posse", "videatur", "percipiendi", "definitur", "Stoicis",
        "Homine", "autem", "summa", "omnis", "animi", "animo", "rationis", "virtus",
        "Optimos", "viros", "hominess", "doctissimos", "virtus", "corporis", "virtuti",
        "anteponatur", "animique", "virtutes", "voluntarias", "vincant", "virtutes",
        "voluntariae", "quidem", "proprie", "virtutes", "appellantur", "multumque",
        "excellunt", "propterea", "quod", "ratione", "gignuntur", "homine", "divinius",
        "aliquid", "rebus", "probabile", "Nimium", "festinanter", "dictum", "videtur",
        "sapientis", "Quamquam", "verba", "quibus", "instituto", "veterum", "utimur",
        "Latinis", "philosophia", "dialectica", "grammatica", "geometria", "musica",
        "quamquam", "Latine", "Etiam", "tractare", "coepimus", "suppeditabit", "nobis",
        "Atticus", "noster", "quantos", "viros", "none", "melius", "quam", "Quae",
        "vobis", "talia", "dicerentur", "qualibus", "uti", "poterat", "expulsus",
        "egens", "palude", "demersus", "tropaeorum", "recordation", "leveret",
        "dolorem",  "audirem", "plane", "probarem",  "haec", "loquitur", "voluptate",
        "nihil", "ponens", "negat", "bene", "cenare", "omnia", "ponat", "voluptate",
        "tamen", "negat", "libenter", "cenasse", "umquam", "Galloniummentiretur",
        "enim", "sed", "bene", "Itaque", "solum", "incommoda", "eveniunt", "inprobis",
        "fugiendam", "inprobitatem", "putamus", "multo", "etiam", "magis", "quod",
        "cuius", "animo", "versatur", "numquam", "sinit", "respirare", "numquam",
        "adquiescere", "Eodem", "Ergo", "eadem", "voluptate", "alteri", "misceat",
        "Fadio", "Gallo", "cuius", "testament", "Aaaaaa", "aaaaab", "aaaaaac", "aaaaaad", "zzzzzzzx",
        "Lorem", "ipsum","dolor","modo", "Epicuri",
        "sint", "Hoc", "autem", "quae", "appetendi", "extrema", "grave", "tamen",
        "puto", "nobis",  "medicina",  "navigationis", "Vivendi", "intellegendum",
        "ipsa", "future", "turpe", "partem", "dixisset", "placet", "complexa", "esse",
        "sententiam", "claris", "viris", "nec", "laudatores", "aliud", "ita",
        "natum", "sic", "ferarum", "natura", "quasdam", "post", "mortem", "formidines",
        "extimescant", "discessu", "suis", "atque", "ipsa", "relinquenda", "luce",
        "moveatur", "naturam", "stupraretur", "Summum", "pecudis", "bonum", "hominis",
        "idem", "mihi", "videri", "potest", "Nihil", "enim", "est", "aliud", "quam",
        "percipi", "nihil", "posse", "videatur", "percipiendi", "definitur", "Stoicis",
        "Homine", "autem", "summa", "omnis", "animi", "animo", "rationis", "virtus",
        "Optimos", "viros", "hominess", "doctissimos", "virtus", "corporis", "virtuti",
        "anteponatur", "animique", "virtutes", "voluntarias", "vincant", "virtutes",
        "voluntariae", "quidem", "proprie", "virtutes", "appellantur", "multumque",
        "excellunt", "propterea", "quod", "ratione", "gignuntur", "homine", "divinius",
        "aliquid", "rebus", "probabile", "Nimium", "festinanter", "dictum", "videtur",
        "sapientis", "Quamquam", "verba", "quibus", "instituto", "veterum", "utimur",
        "Latinis", "philosophia", "dialectica", "grammatica", "geometria", "musica",
        "quamquam", "Latine", "Etiam", "tractare", "coepimus", "suppeditabit", "nobis",
        "Atticus", "noster", "quantos", "viros", "none", "melius", "quam", "Quae",
        "vobis", "talia", "dicerentur", "qualibus", "uti", "poterat", "expulsus",
        "egens", "palude", "demersus", "tropaeorum", "recordation", "leveret",
        "dolorem",  "audirem", "plane", "probarem",  "haec", "loquitur", "voluptate",
        "nihil", "ponens", "negat", "bene", "cenare", "omnia", "ponat", "voluptate",
        "tamen", "negat", "libenter", "cenasse", "umquam", "Galloniummentiretur",
        "enim", "sed", "bene", "Itaque", "solum", "incommoda", "eveniunt", "inprobis",
        "fugiendam", "inprobitatem", "putamus", "multo", "etiam", "magis", "quod",
        "cuius", "animo", "versatur", "numquam", "sinit", "respirare", "numquam",
        "adquiescere", "Eodem", "Ergo", "eadem", "voluptate", "alteri", "misceat",
        "Fadio", "Gallo", "cuius", "testament", "Aaaaaa", "aaaaab", "aaaaaac", "aaaaaad", "zzzzzzzx",
    };
}